### PR TITLE
feature: all components are related and able to be pakcaged and imported

### PR DESCRIPTION
**Pull request by Risk-taker0501**
#9  #10

### CODE REVIEW

**Comment by screw123** [comment]
Also can we try to move as much packages to peerDependency?  e.g emotion and chakra ui, framer-motion, i18next related, react-dom, they should all be using in our other main projects.  Not moving will lead to version issues.
`jest-environment-jsdom` can you check why we need this package?  Is it for test?  If it is, should it be in dependency or devDependency?

**Comment by screw123** [comment]
@Risk-taker0501 Also, pls use npm instead of yarn.

**Comment by Risk-taker0501** [comment]
I will check and fix following your opinion, asap.

**Comment by screw123** [comment]
Please link the PR back to task

**Comment by Risk-taker0501** [comment]
Okay. I got it. I will link PR to task

**Comment by screw123** [comment]
In rollup.config.js, line 9, you:

```
const input = './src/App.tsx';
```

However in App.tsx, you only:

```
export default App;
```

As said I expect to export all individual components so I have flexibility to compose them whichever way we need in main projects.
Please help to do the exports.

**Comment by Risk-taker0501** [comment]
I think this pull request has to be removed.
I will create PR, today after fix.

**Comment by Risk-taker0501** [comment]
How do you think, close this PR or merge, now?

**Comment by screw123** [comment]
> How do you think, close this PR or merge, now?

Both are fine.  Your work is not bad as a first PR.  Just some coop issues.  Also in future, I will need your help to read clearly the task spec, think through it, especially think through when you know more about the repo / project when you work longer.

**Comment by Risk-taker0501** [comment]
I think that first, merge this PR and based on this PR, I will fix asap following your opinion and create new PR.
Is this okay?

**Comment by screw123** [comment]
You can actually build a new PR based on this PR
Or, you can continue to submit code to this PR

Do you use GitHub Desktop?  If yes, you can easily swap to the PR branch and send in new commits

**Comment by Risk-taker0501** [comment]
I will continue to submit new code to this PR.

**Comment by Risk-taker0501** [comment]
- changed to use npm from yarn.
- fixed peerDpendencies
- deleted unusable packages
- jest environment is necessary
- liked PR to tasks
- change project to be able to run in React(16~18)

**Comment by screw123** [comment]
Hi @Risk-taker0501 thanks for the hard work.
No time to test the code, but I trust the code must be runnable.  It's my very bad habit of merging uncertain code into main branch.  Let me do it once to keep the project going.  I will come back and test tomorrow.

**Pull request merged**
